### ISSUE TITLE
Support extra classes

### ISSUE THREAD

**Issue by monolithed** [Monar/bem-names#1]
It would be nice to support additional extra classes like https://github.com/marcohamersma/react-bem-helper

**Comment by Monar** [comment]
Are you referring to:
```js
customBemNames({ stringModifiers: 'passThrough' }, 'block', 'element', ['modifier'], 'extra')
// will return: "block__element block__element--modifier extra"
```

**Comment by monolithed** [comment]
Yep

**Comment by Monar** [comment]
So its already supported :D 
https://www.npmjs.com/package/bem-names#bem-with-regular-classes

I'll try to improve the readme file.
